[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
  -D CRSF_UART_NUM=1
  -D CRSF_UART_RX_PIN=16
  -D PWM_PIN_CH1=18
  -D PWM_PIN_CH2=19
  -D PWM_PIN_CH3=21
